#!/usr/bin/env bash
#scriopt that kills process



sigquit_handler() {
    rm -f "/var/run/myscript.pid"
    exit 0
}
sigint_handler() {
    echo "Y U no love me?!"
}

sigterm_handler() {
    echo "I hate the kill command"
}
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT


echo "$$" > /var/run/myscript.pid

echo "To infinity and beyond!"
while true;
do
  sleep 1
done
