#!/usr/bin/env bash
#scriopt that kills process


sigterm_handler() {
    echo "I hate the kill command"
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    echo "Deleting PID file and terminating script"
    rm -f /var/run/myscript.pid
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

echo "$$" > /var/run/myscript.pid

echo "To infinity and beyond indefinitely"
while true;
do
    sleep 1
done
