#!/usr/bin/env bash
#scriopt that kills process


case "$1" in
    start|stop|restart)
        /path/to/manage_my_process "$1"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
