#!/usr/bin/env bash
#scriopt that prints text indefinitely

PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$PID" ];
then
    kill $PID
    echo "Process 4-to_infinity_and_beyond stopped successfully."
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
