#!/usr/bin/env bash
#scriopt that prints text indefinitely

if [[ $(pgrep -f "4-to_infinity_and_beyond") -ne 0 ]];
then
    PID=$(pgrep -f "4-to_infinity_and_beyond")

    if [ -n "$PID" ];
    then
        kill "$PID"
    fi
fi
