#!/usr/bin/env bash
#scriopt that kills process

if pgrep -f "4-to_infinity_and_beyond" >/dev/null;
then
    pkill -f "4-to_infinity_and_beyond"
    echo "Process 4-to_infinity_and_beyond stopped successfully."
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
