#!/usr/bin/env bash
#scriopt that kills process



trap 'echo "Received SIGTERM signal. Press Ctrl+C to exit gracefully." && exit 0' SIGTERM
while true;
do
  echo "To infinity and beyond"
  sleep 2
done

