#!/usr/bin/env bash
#scriopt that prints text

count=0
while [ $count -le 10 ];
do
    if [ $count -eq 9 ];
    then
	echo "Best School"
        echo "Hi"
    else
	echo "Best School"
    fi
    ((count++))
done
