#!/usr/bin/env bash
#scriopt that prints text

count=1
while [ $count -le 20 ];
do
    case $count in
	4)
            echo "bad luck from China"
            ;;
	9)
            echo "bad luck from Japan"
            ;;
        19)
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
	    ;;
    esac	    
    ((count++))
done
