#!/usr/bin/env bash
#scriopt that prints text

hours=0
minutes=1
while [ $hours -le 10 ];
do
    while [ $minutes -le 59 ];
    do
	printf "%02d:%02d\n" $hours $minutes
        ((minutes++))
    done
    ((hours++))
    minutes=0
done
