#!/usr/bin/env bash
#scriopt that prints text

hours=0
while [ $hours -le 12 ];
do
    minutes=1
    while [ $minutes -le 59 ];
    do
	printf "%02d\n" $hours $minutes
        ((minutes++))
    done
    ((hours++))
done
